language: julia
sudo: required
dist: trusty
julia:
  - nightly
  - 0.7
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false

before_install:
  - sudo apt-get -qq update

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'using UUIDs; write("Project.toml", replace(read("Project.toml", String), r"uuid = .*?\n" =>"uuid = \"$(uuid4())\""));
                                 import Pkg; Pkg.instantiate(); Pkg.test(; coverage=true)'

after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'